"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const addresses_1 = require("../../controllers/addresses");
const middlewares_1 = require("../../middlewares");
const AddressRoute = (0, express_1.Router)();
AddressRoute.use(middlewares_1.MiddleWares.authorization);
AddressRoute.get('/', addresses_1.AddressController.findUserAddress);
AddressRoute.post('/', addresses_1.AddressController.createUserAddress);
AddressRoute.get('/admins', addresses_1.AddressController.findAdminAddress);
AddressRoute.post('/admins', addresses_1.AddressController.createAdminAddress);
AddressRoute.delete('/', addresses_1.AddressController.remove);
AddressRoute.get('/provinces', addresses_1.AddressController.findProvinces);
AddressRoute.get('/regencies/:provinceId', addresses_1.AddressController.findRegencies);
AddressRoute.get('/districts/:regencyId', addresses_1.AddressController.findDistricts);
AddressRoute.get('/villages/:districtId', addresses_1.AddressController.findVillages);
exports.default = AddressRoute;
