"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const middlewares_1 = require("../../middlewares");
const paymentMethod_1 = require("../../controllers/paymentMethod");
const PaymentMethodRouter = (0, express_1.Router)();
PaymentMethodRouter.get('/', paymentMethod_1.PaymentMethodController.findAll);
PaymentMethodRouter.get('/detail/:paymentMethodId', paymentMethod_1.PaymentMethodController.findDetail);
PaymentMethodRouter.post('/', middlewares_1.MiddleWares.authorization, paymentMethod_1.PaymentMethodController.create);
PaymentMethodRouter.patch('/', middlewares_1.MiddleWares.authorization, paymentMethod_1.PaymentMethodController.update);
PaymentMethodRouter.delete('/:paymentMethodId', middlewares_1.MiddleWares.authorization, paymentMethod_1.PaymentMethodController.remove);
exports.default = PaymentMethodRouter;
