"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const middlewares_1 = require("../../middlewares");
const products_1 = require("../../controllers/products");
const promotions_1 = require("../../controllers/promotions");
const ProductRoute = (0, express_1.Router)();
ProductRoute.get('/', products_1.ProductController.findAll);
ProductRoute.get('/admin', products_1.ProductController.findAllProductsAdmin);
ProductRoute.get('/highlights', promotions_1.PromotionController.findAllPromotion);
ProductRoute.get('/detail/:productId', products_1.ProductController.findOne);
ProductRoute.post('/', middlewares_1.MiddleWares.authorization, middlewares_1.MiddleWares.allowAppRoles('admin', 'superAdmin'), products_1.ProductController.create);
ProductRoute.patch('/', middlewares_1.MiddleWares.authorization, middlewares_1.MiddleWares.allowAppRoles('admin', 'superAdmin'), products_1.ProductController.update);
ProductRoute.delete('/', middlewares_1.MiddleWares.authorization, middlewares_1.MiddleWares.allowAppRoles('admin', 'superAdmin'), products_1.ProductController.remove);
ProductRoute.post('/upload-excel', middlewares_1.MiddleWares.authorization, middlewares_1.MiddleWares.allowAppRoles('admin', 'superAdmin'), products_1.ProductController.upload);
ProductRoute.get('/upload-histories', middlewares_1.MiddleWares.authorization, middlewares_1.MiddleWares.allowAppRoles('admin', 'superAdmin'), products_1.ProductController.uploadHistories);
exports.default = ProductRoute;
